# =========================
# Imports
# =========================
from rich.theme import Theme
# =========================
# Styling / Themes
# =========================
STYLES = {
    "classic": Theme({
        "rule": "gold3",
        "divider": "gold3",
        "label": "gold3",
        "table.header": "bold gold3",
        "table.title": "bold gold3",
        "table.border": "gold3",
        "app.title": "bold gold3",
        "title": "bold orange3",
        "app.weather": "bold green3",
        "money.good": "bold green3",
        "money.bad": "bold red3",
        "money.neutral": "bold khaki3",
        "panel.border": "gold3",
    }),
    "midnight": Theme({
        "rule": "bright_cyan",
        "divider": "bright_cyan",
        "label": "bright_cyan",
        "table.header": "bold bright_cyan",
        "table.title": "bold bright_cyan",
        "table.border": "bright_cyan",
        "app.title": "bold bright_cyan",
        "title": "bold orange1",
        "app.weather": "cyan",
        "money.good": "bold bright_green",
        "money.bad": "bold bright_red",
        "money.neutral": "bold bright_cyan",
        "panel.border": "bright_cyan",
    }),
    "forest": Theme({
        "rule": "green3",
        "divider": "green3",
        "label": "green3",
        "table.header": "bold green3",
        "table.title": "bold green3",
        "table.border": "green3",
        "app.title": "bold green3",
        "title": "bold dark_orange3",
        "app.weather": "green",
        "money.good": "bold green3",
        "money.bad": "bold red3",
        "money.neutral": "bold green3",
        "panel.border": "green3",
    }),
    "sunset": Theme({
        "rule": "magenta3",
        "divider": "magenta3",
        "label": "magenta3",
        "table.header": "bold magenta3",
        "table.title": "bold magenta3",
        "table.border": "magenta3",
        "app.title": "bold magenta3",
        "title": "bold orange3",
        "app.weather": "bold yellow3",
        "money.good": "bold green3",
        "money.bad": "bold red3",
        "money.neutral": "bold magenta3",
        "panel.border": "magenta3",
    }),
    "high_contrast": Theme({
        "rule": "white",
        "divider": "white",
        "label": "bold white",
        "table.header": "bold white on black",
        "table.title": "bold white",
        "table.border": "white",
        "app.title": "bold white",
        "title": "bold bright_white",
        "app.weather": "bold bright_white",
        "money.good": "bold bright_green",
        "money.bad": "bold bright_red",
        "money.neutral": "bold bright_white",
        "panel.border": "white",
    }),
}
